server:
#  context-path: /blb
  port: 8803
  
spring:
  freemarker:
    suffix: .html
    enableed: true
    template-loader-path: classpath:/templates/
    charset: UTF-8
    request-context-attribute: request
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blb?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mybatis:
   mapper-locations: classpath:mybatis/**/*.xml
   type-aliases-pakage: com.blb.**.mapper
  redis:
   database: 0
   host: 192.168.0.104
   password: 
   timeout: 0
   pool:
    max-wait: -1
    max-active: 8
    max-idle: 8
    min-idle: 0


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql